In [1]:
%%capture
%load_ext sql
%sql sqlite:///factbook.db

In [2]:
%%sql
SELECT * FROM sqlite_master
WHERE type='table';

 * sqlite:///factbook.db
Done.

[('table', 'sqlite_sequence', 'sqlite_sequence', 3, 'CREATE TABLE sqlite_sequence(name,seq)'),
 ('table', 'facts', 'facts', 47, 'CREATE TABLE "facts" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "code" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "area" integer, "a ... (4 characters truncated) ... land" integer, "area_water" integer, "population" integer, "population_growth" float, "birth_rate" float, "death_rate" float, "migration_rate" float)')]

In [3]:
%%sql
--Checking column headers

SELECT * FROM facts
LIMIT 5

 * sqlite:///factbook.db
Done.

[(1, 'af', 'Afghanistan', 652230, 652230, 0, 32564342, 2.32, 38.57, 13.89, 1.51),
 (2, 'al', 'Albania', 28748, 27398, 1350, 3029278, 0.3, 12.92, 6.58, 3.3),
 (3, 'ag', 'Algeria', 2381741, 2381741, 0, 39542166, 1.84, 23.67, 4.31, 0.92),
 (4, 'an', 'Andorra', 468, 468, 0, 85580, 0.12, 8.13, 6.96, 0.0),
 (5, 'ao', 'Angola', 1246700, 1246700, 0, 19625353, 2.78, 38.78, 11.49, 0.46)]

In [4]:
%%sql

--Finding min and max

SELECT min(population), max(population), 
min(population_growth), max(population_growth)
FROM facts

 * sqlite:///factbook.db
Done.

[(0, 7256490011, 0.0, 4.02)]

In [5]:
%%sql
--Finding smallest and largest poulations in dataset


SELECT * FROM facts
where population== (SELECT min(population) FROM facts)
or population== (SELECT max(population) FROM facts)

 * sqlite:///factbook.db
Done.

[(250, 'ay', 'Antarctica', None, 280000, None, 0, None, None, None, None),
 (261, 'xx', 'World', None, None, None, 7256490011, 1.08, 18.6, 7.8, None)]

In [6]:
%%sql

--Finding largest population size excluding 'World'

SELECT min(population), max(population), 
min(population_growth), max(population_growth)
FROM facts
WHERE name<>'World'

 * sqlite:///factbook.db
Done.

[(0, 1367485388, 0.0, 4.02)]

In [7]:
%%sql
--Finding average population and area of dataset

SELECT avg(population), avg(area) FROM facts

 * sqlite:///factbook.db
Done.

[(62094928.32231405, 555093.546184739)]

In [8]:
%%sql

/*Finding which countries have both above average populations
and below average area*/

SELECT * FROM facts
WHERE population> (SELECT avg(population) FROM facts) AND
area< (SELECT avg(area) FROM facts)

 * sqlite:///factbook.db
Done.

[(14, 'bg', 'Bangladesh', 148460, 130170, 18290, 168957745, 1.6, 21.14, 5.61, 0.46),
 (65, 'gm', 'Germany', 357022, 348672, 8350, 80854408, 0.17, 8.47, 11.42, 1.24),
 (85, 'ja', 'Japan', 377915, 364485, 13430, 126919659, 0.16, 7.93, 9.51, 0.0),
 (138, 'rp', 'Philippines', 300000, 298170, 1830, 100998376, 1.61, 24.27, 6.11, 2.09),
 (173, 'th', 'Thailand', 513120, 510890, 2230, 67976405, 0.34, 11.19, 7.8, 0.0),
 (185, 'uk', 'United Kingdom', 243610, 241930, 1680, 64088222, 0.54, 12.17, 9.35, 2.54),
 (192, 'vm', 'Vietnam', 331210, 310070, 21140, 94348835, 0.97, 15.96, 5.93, 0.3)]

In [9]:
%%sql
--Finding country with the largest population

SELECT * FROM facts
WHERE population== (SELECT max(population) FROM facts
                   WHERE name<> 'World')

 * sqlite:///factbook.db
Done.

[(37, 'ch', 'China', 9596960, 9326410, 270550, 1367485388, 0.45, 12.49, 7.53, 0.44)]

In [10]:
%%sql

--Finding countries with the highest water-to-land ratios

SELECT *,CAST(area_water AS FLOAT)/area_land as water_land_ratio, area_land/
area_water as land_water_ratio FROM facts
WHERE water_land_ratio<>'None'
ORDER BY water_land_ratio DESC

 * sqlite:///factbook.db
Done.

[(228, 'io', 'British Indian Ocean Territory', 54400, 60, 54340, None, None, None, None, None, 905.6666666666666, 0),
 (247, 'vq', 'Virgin Islands', 1910, 346, 1564, 103574, 0.59, 10.31, 8.54, 7.67, 4.520231213872832, 0),
 (246, 'rq', 'Puerto Rico', 13791, 8870, 4921, 3598357, 0.6, 10.86, 8.67, 8.15, 0.5547914317925592, 1),
 (12, 'bf', 'Bahamas, The', 13880, 10010, 3870, 324597, 0.85, 15.5, 7.05, 0.0, 0.3866133866133866, 2),
 (71, 'pu', 'Guinea-Bissau', 36125, 28120, 8005, 1726170, 1.91, 33.38, 14.33, 0.0, 0.2846728307254623, 3),
 (106, 'mi', 'Malawi', 118484, 94080, 24404, 17964697, 3.32, 41.56, 8.41, 0.0, 0.25939625850340137, 3),
 (125, 'nl', 'Netherlands', 41543, 33893, 7650, 16947904, 0.41, 10.83, 8.66, 1.95, 0.22571032366565366, 4),
 (182, 'ug', 'Uganda', 241038, 197100, 43938, 37101745, 3.24, 43.79, 10.69, 0.74, 0.22292237442922375, 4),
 (56, 'er', 'Eritrea', 117600, 101000, 16600, 6527689, 2.25, 30.0, 7.52, 0.0, 0.16435643564356436, 6),
 (99, 'li', 'Liberia', 111369, 96320, 15049, 4195666, 2.47, 34.41, 9.69, 0.0, 0.15623961794019933, 6),
 (14, 'bg', 'Bangladesh', 148460, 130170, 18290, 168957745, 1.6, 21.14, 5.61, 0.46, 0.1405085657217485, 7),
 (63, 'ga', 'Gambia, The', 11300, 10120, 1180, 1967709, 2.16, 30.86, 7.15, 2.12, 0.116600790513834, 8),
 (196, 'tw', 'Taiwan', 35980, 32260, 3720, 23415126, 0.23, 8.47, 7.11, 0.89, 0.1153130812151271, 8),
 (60, 'fi', 'Finland', 338145, 303815, 34330, 5476922, 0.4, 10.72, 9.83, 3.1, 0.11299639583299047, 8),
 (77, 'in', 'India', 3287263, 2973193, 314070, 1251695584, 1.22, 19.55, 7.32, 0.04, 0.10563390940312317, 9),
 (32, 'ca', 'Canada', 9984670, 9093507, 891163, 35099836, 0.75, 10.28, 8.42, 5.66, 0.09799992456155804, 10),
 (168, 'sw', 'Sweden', 450295, 410335, 39960, 9801616, 0.8, 11.99, 9.4, 5.42, 0.09738384490720996, 10),
 (38, 'co', 'Colombia', 1138910, 1038700, 100210, 46736728, 1.04, 16.47, 5.4, 0.64, 0.09647636468662751, 10),
 (25, 'bx', 'Brunei', 5765, 5265, 500, 429646, 1.62, 17.32, 3.52, 2.43, 0.0949667616334283, 10),
 (72, 'gy', 'Guyana', 214969, 196849, 18120, 735222, 0.02, 15.59, 7.32, 8.06, 0.09205025171578214, 10),
 (209, 'fp', 'French Polynesia', 4167, 3827, 340, 282703, 0.94, 15.22, 5.02, 0.84, 0.08884243532793311, 11),
 (127, 'nu', 'Nicaragua', 130370, 119990, 10380, 5907881, 1.0, 18.03, 5.08, 3.0, 0.08650720893407784, 11),
 (29, 'by', 'Burundi', 27830, 25680, 2150, 10742276, 3.28, 42.01, 9.27, 0.0, 0.0837227414330218, 11),
 (79, 'ir', 'Iran', 1648195, 1531595, 116600, 81824270, 1.2, 17.99, 5.94, 0.07, 0.07612978626856316, 13),
 (186, 'us', 'United States', 9826675, 9161966, 664709, 321368864, 0.78, 12.49, 8.15, 3.86, 0.07255091319919764, 13),
 (172, 'tz', 'Tanzania', 947300, 885800, 61500, 51045882, 2.79, 36.39, 8.0, 0.54, 0.06942876495822985, 14),
 (192, 'vm', 'Vietnam', 331210, 310070, 21140, 94348835, 0.97, 15.96, 5.93, 0.3, 0.06817815332021801, 14),
 (144, 'rw', 'Rwanda', 26338, 24668, 1670, 12661733, 2.56, 33.75, 8.96, 0.85, 0.06769904329495703, 14),
 (57, 'en', 'Estonia', 45228, 42388, 2840, 1265420, 0.55, 10.51, 12.4, 3.6, 0.06700009436633009, 14),
 (130, 'no', 'Norway', 323802, 304282, 19520, 5207689, 1.13, 12.14, 8.12, 7.25, 0.06415101780585115, 15),
 (8, 'am', 'Armenia', 29743, 28203, 1540, 3056382, 0.15, 13.61, 9.34, 5.8, 0.054604120129064286, 18),
 (178, 'ts', 'Tunisia', 163610, 155360, 8250, 11037225, 0.89, 16.64, 5.98, 1.73, 0.05310247167868177, 18),
 (188, 'uz', 'Uzbekistan', 447400, 425400, 22000, 29199942, 0.93, 17.0, 5.3, 2.37, 0.051716031969910675, 19),
 (78, 'id', 'Indonesia', 1904569, 1811569, 93000, 255993674, 0.92, 16.72, 6.37, 1.16, 0.0513367141963679, 19),
 (166, 'ns', 'Suriname', 163820, 156000, 7820, 579633, 1.08, 16.34, 6.13, 0.56, 0.05012820512820513, 19),
 (2, 'al', 'Albania', 28748, 27398, 1350, 3029278, 0.3, 12.92, 6.58, 3.3, 0.04927366961092051, 20),
 (66, 'gh', 'Ghana', 238533, 227533, 11000, 26327649, 2.18, 31.09, 7.22, 2.02, 0.048344635723169826, 20),
 (11, 'aj', 'Azerbaijan', 86600, 82629, 3971, 9780780, 0.96, 16.64, 7.07, 0.0, 0.048058187803313605, 20),
 (175, 'to', 'Togo', 56785, 54385, 2400, 7552318, 2.69, 34.13, 7.26, 0.0, 0.044129815206398824, 22),
 (143, 'rs', 'Russia', 17098242, 16377742, 720500, 142423773, 0.04, 11.6, 13.69, 1.69, 0.04399263341674328, 22),
 (94, 'kg', 'Kyrgyzstan', 199951, 191801, 8150, 5664939, 1.11, 22.98, 6.65, 5.22, 0.04249195781043894, 23),
 (176, 'tn', 'Tonga', 747, 717, 30, 106501, 0.03, 23.0, 4.85, 17.84, 0.04184100418410042, 23),
 (183, 'up', 'Ukraine', 603550, 579330, 24220, 44429471, 0.6, 10.72, 14.46, 2.25, 0.04180691488443547, 23),
 (102, 'lh', 'Lithuania', 65300, 62680, 2620, 2884433, 1.04, 10.1, 14.27, 6.27, 0.041799617102744095, 23),
 (254, 'we', 'West Bank', 5860, 5640, 220, 2785366, 1.95, 22.99, 3.5, 0.0, 0.03900709219858156, 25),
 (62, 'gb', 'Gabon', 267667, 257667, 10000, 1705336, 1.93, 34.49, 13.12, 2.03, 0.03880978161735884, 25),
 (180, 'tx', 'Turkmenistan', 488100, 469930, 18170, 5231422, 1.14, 19.4, 6.13, 1.84, 0.038665333134722195, 25),
 (75, 'hu', 'Hungary', 93028, 89608, 3420, 9897541, 0.22, 9.16, 12.73, 1.33, 0.038166235157575217, 26),
 (96, 'lg', 'Latvia', 64589, 62249, 2340, 1986705, 1.06, 10.0, 14.31, 6.26, 0.03759096531671192, 26),
 (142, 'ro', 'Romania', 238391, 229891, 8500, 21666350, 0.3, 9.14, 11.9, 0.24, 0.03697404422095689, 27),
 (85, 'ja', 'Japan', 377915, 364485, 13430, 126919659, 0.16, 7.93, 9.51, 0.0, 0.036846509458551106, 27),
 (28, 'bm', 'Burma', 676578, 653508, 23070, 56320206, 1.01, 18.39, 7.96, 0.28, 0.03530178666519767, 28),
 (40, 'cg', 'Congo, Democratic Republic of the', 2344858, 2267048, 77810, 79375136, 2.45, 34.88, 10.07, 0.27, 0.03432216697661452, 29),
 (191, 've', 'Venezuela', 912050, 882050, 30000, 29275460, 1.39, 19.16, 5.31, 0.0, 0.034011677342554274, 29),
 (132, 'pk', 'Pakistan', 796095, 770875, 25220, 199085847, 1.46, 22.58, 6.49, 1.54, 0.03271606940165397, 30),
 (204, 'hk', 'Hong Kong', 1108, 1073, 35, 7141106, 0.38, 9.23, 7.07, 1.68, 0.032618825722273995, 30),
 (159, 'bp', 'Solomon Islands', 28896, 27986, 910, 622469, 2.02, 25.77, 3.85, 1.75, 0.03251625812906453, 30),
 (169, 'sz', 'Switzerland', 41277, 39997, 1280, 8121830, 0.71, 10.5, 8.13, 4.74, 0.032002400180013504, 31),
 (116, 'md', 'Moldova', 33851, 32891, 960, 3546847, 1.03, 12.0, 12.59, 9.67, 0.029187315679061143, 34),
 (37, 'ch', 'China', 9596960, 9326410, 270550, 1367485388, 0.45, 12.49, 7.53, 0.44, 0.029009018475490568, 34),
 (91, 'ks', 'Korea, South', 99720, 96920, 2800, 49115196, 0.14, 8.19, 6.75, 0.0, 0.028889806025588115, 34),
 (139, 'pl', 'Poland', 312685, 304255, 8430, 38562189, 0.09, 9.74, 10.19, 0.46, 0.027707022070302872, 36),
 (76, 'ic', 'Iceland', 103000, 100250, 2750, 331918, 1.21, 13.91, 6.28, 4.43, 0.02743142144638404, 36),
 (119, 'mj', 'Montenegro', 13812, 13452, 360, 647073, 0.42, 10.42, 9.43, None, 0.026761819803746655, 37),
 (124, 'np', 'Nepal', 147181, 143351, 3830, 31551305, 1.79, 20.64, 6.56, 3.86, 0.02671763712844696, 37),
 (23, 'bc', 'Botswana', 581730, 566730, 15000, 2182719, 1.21, 20.96, 13.39, 4.56, 0.026467630088401885, 37),
 (95, 'la', 'Laos', 236800, 230800, 6000, 6911544, 1.55, 24.25, 7.63, 1.09, 0.025996533795493933, 38),
 (30, 'cb', 'Cambodia', 181035, 176515, 4520, 15708756, 1.58, 23.83, 7.68, 0.32, 0.025606888932951873, 39),
 (83, 'it', 'Italy', 301340, 294140, 7200, 61855120, 0.27, 8.74, 10.19, 4.1, 0.024478139661385734, 40),
 (52, 'ec', 'Ecuador', 283561, 276841, 6720, 15868396, 1.35, 18.51, 5.06, 0.0, 0.02427386116940771, 41),
 (65, 'gm', 'Germany', 357022, 348672, 8350, 80854408, 0.17, 8.47, 11.42, 1.24, 0.023948008443465493, 41),
 (136, 'pa', 'Paraguay', 406752, 397302, 9450, 6783272, 1.16, 16.37, 4.68, 0.07, 0.023785432743857318, 42),
 (16, 'bo', 'Belarus', 207600, 202900, 4700, 9589689, 0.2, 10.7, 13.36, 0.7, 0.023164120256283883, 43),
 (135, 'pp', 'Papua New Guinea', 462840, 452860, 9980, 6672429, 1.78, 24.38, 6.53, 0.0, 0.022037715850373184, 45),
 (26, 'bu', 'Bulgaria', 110879, 108489, 2390, 7186893, 0.58, 8.92, 14.44, 0.29, 0.022029883213966393, 45),
 (152, 'sg', 'Senegal', 196722, 192530, 4192, 13975834, 2.45, 34.52, 8.46, 1.59, 0.02177323014595128, 45),
 (82, 'is', 'Israel', 20770, 20330, 440, 8049314, 1.56, 18.48, 5.15, 2.24, 0.02164289227742253, 46),
 (47, 'ez', 'Czech Republic', 78867, 77247, 1620, 10644842, 0.16, 9.63, 10.34, 2.33, 0.02097168822090178, 47),
 (81, 'ei', 'Ireland', 70273, 68883, 1390, 4892305, 1.25, 14.84, 6.48, 4.09, 0.02017914434621024, 49),
 (88, 'ke', 'Kenya', 580367, 569140, 11227, 45925301, 1.93, 26.4, 6.89, 0.22, 0.019726253645851635, 50),
 (35, 'cd', 'Chad', None, 1259200, 24800, 11631456, 1.89, 36.6, 14.28, 3.45, 0.019695044472681066, 50),
 (157, 'lo', 'Slovakia', 49035, 48105, 930, 5445027, 0.02, 9.91, 9.74, 0.04, 0.01933270969753664, 51),
 (24, 'br', 'Brazil', 8515770, 8358140, 157630, 204259812, 0.77, 14.46, 6.58, 0.14, 0.018859459161966657, 53),
 (171, 'ti', 'Tajikistan', 144100, 141510, 2590, 8191958, 1.71, 24.38, 6.18, 1.15, 0.018302593456292843, 54),
 (179, 'tu', 'Turkey', 783562, 769632, 13930, 79414269, 1.26, 16.33, 5.88, 2.16, 0.018099559269884827, 55),
 (19, 'bn', 'Benin', 112622, 110622, 2000, 10448647, 2.78, 36.02, 8.21, 0.0, 0.018079586339064563, 55),
 (10, 'au', 'Austria', 83871, 82445, 1426, 8665550, 0.55, 9.41, 9.42, 5.56, 0.017296379404451452, 57),
 (97, 'le', 'Lebanon', 10400, 10230, 170, 6184701, 0.86, 14.59, 4.88, 1.1, 0.016617790811339198, 60),
 (121, 'mz', 'Mozambique', 799380, 786380, 13000, 25303113, 2.45, 38.58, 12.1, 1.98, 0.016531447900506115, 60),
 (36, 'ci', 'Chile', 756102, 743812, 12290, 17508260, 0.82, 13.83, 6.0, 0.34, 0.01652299236903949, 60),
 (146, 'st', 'Saint Lucia', 616, 606, 10, 163922, 0.34, 13.7, 7.42, 2.93, 0.0165016501650165, 60),
 (160, 'so', 'Somalia', 637657, 627337, 10320, 10616380, 1.83, 40.45, 13.62, 8.49, 0.016450488334021428, 60),
 (211, 'nc', 'New Caledonia', 18575, 18275, 300, 271615, 1.38, 15.33, 5.52, 4.01, 0.016415868673050615, 60),
 (109, 'ml', 'Mali', 1240192, 1220190, 20002, 16955536, 2.98, 44.99, 12.89, 2.26, 0.016392529032363812, 61),
 (69, 'gt', 'Guatemala', 108889, 107159, 1730, 14918999, 1.82, 24.89, 4.77, 1.97, 0.016144234268703515, 61),
 (7, 'ar', 'Argentina', 2780400, 2736690, 43710, 43431886, 0.93, 16.64, 7.33, 0.0, 0.015971849204696183, 62),
 (48, 'da', 'Denmark', 43094, 42434, 660, 5581503, 0.22, 10.27, 10.25, 2.2, 0.015553565537069332, 64),
 (54, 'es', 'El Salvador', 21041, 20721, 320, 6141350, 0.25, 16.46, 5.69, 8.28, 0.015443270112446311, 64),
 (164, 'ce', 'Sri Lanka', 65610, 64630, 980, 22053488, 0.84, 15.85, 6.11, 1.35, 0.01516323688689463, 65),
 (84, 'jm', 'Jamaica', 10991, 10831, 160, 2950210, 0.68, 18.16, 6.7, 4.66, 0.01477241251961961, 67),
 (156, 'sn', 'Singapore', 697, 687, 10, 5674472, 1.89, 8.27, 3.43, 14.05, 0.01455604075691412, 68),
 (134, 'pm', 'Panama', 75420, 74340, 1080, 3657024, 1.32, 18.32, 4.81, 0.28, 0.014527845036319613, 68),
 (129, 'ni', 'Nigeria', 923768, 910768, 13000, 181562056, 2.45, 37.64, 12.9, 0.22, 0.014273667937389104, 70),
 (21, 'bl', 'Bolivia', 1098581, 1083301, 15280, 10800882, 1.56, 22.76, 6.52, 0.62, 0.014105036365700761, 70),
 (43, 'iv', "Cote d'Ivoire", 322463, 318003, 4460, 23295302, 1.91, 28.67, 9.55, 0.0, 0.014025024921148543, 71),
 (163, 'sp', 'Spain', 505370, 498980, 6390, 48146134, 0.89, 9.64, 9.04, 8.31, 0.012806124493967693, 78),
 (194, 'za', 'Zambia', 752618, 743398, 9220, 15066266, 2.88, 42.13, 12.67, 0.68, 0.012402508481324943, 80),
 (44, 'hr', 'Croatia', 56594, 55974, 620, 4464844, 0.13, 9.45, 12.18, 1.39, 0.011076571265230286, 90),
 (104, 'mk', 'Macedonia', 25713, 25433, 280, 2096015, 0.2, 11.55, 9.08, 0.48, 0.011009318601816538, 90),
 (114, 'mx', 'Mexico', 1964375, 1943945, 20430, 121736809, 1.18, 18.78, 5.26, 1.68, 0.010509556597537481, 95),
 (195, 'zi', 'Zimbabwe', 390757, 386847, 3910, 14229541, 2.21, 32.26, 10.13, 0.0, 0.010107355104214328, 98),
 (67, 'gr', 'Greece', 131957, 130647, 1310, 10775643, 0.01, 8.66, 11.09, 2.32, 0.010027019372813766, 99),
 (45, 'cu', 'Cuba', 110860, 109820, 1040, 11031433, 0.15, 9.9, 7.72, 3.66, 0.00947004188672373, 105),
 (105, 'ma', 'Madagascar', 587041, 581540, 5501, 23812681, 2.58, 32.61, 6.81, 0.0, 0.009459366509612408, 105),
 (87, 'kz', 'Kazakhstan', 2724900, 2699700, 25200, 18157122, 1.14, 19.15, 8.21, 0.41, 0.009334370485609512, 107),
 (167, 'wz', 'Swaziland', 17364, 17204, 160, 1435613, 1.11, 24.67, 13.56, 0.0, 0.009300162752848175, 107),
 (170, 'sy', 'Syria', 185180, 183630, 1550, 17064854, 0.16, 22.17, 4.0, 19.79, 0.008440886565376027, 118),
 (17, 'be', 'Belgium', 30528, 30278, 250, 11323973, 0.76, 11.41, 9.63, 5.87, 0.008256820133430213, 121),
 (9, 'as', 'Australia', 7741220, 7682300, 58920, 22751014, 1.07, 12.15, 7.14, 5.65, 0.007669578121135597, 130),
 (51, 'dr', 'Dominican Republic', 48670, 48320, 350, 10478756, 1.23, 18.73, 4.55, 1.91, 0.007243377483443708, 138),
 (18, 'bh', 'Belize', 22966, 22806, 160, 347369, 1.87, 24.68, 5.97, 0.0, 0.00701569762343243, 142),
 (185, 'uk', 'United Kingdom', 243610, 241930, 1680, 64088222, 0.54, 12.17, 9.35, 2.54, 0.006944157400901087, 144),
 (73, 'ha', 'Haiti', 27750, 27560, 190, 10110019, 1.17, 22.31, 7.83, 2.76, 0.006894049346879536, 145),
 (187, 'uy', 'Uruguay', 176215, 175015, 1200, 3341893, 0.27, 13.07, 9.45, 0.9, 0.006856555152415508, 145),
 (118, 'mg', 'Mongolia', 1564116, 1553556, 10560, 2992908, 1.31, 20.25, 6.35, 0.84, 0.006797308883619258, 147),
 (140, 'po', 'Portugal', 92090, 91470, 620, 10825309, 0.09, 9.27, 11.02, 2.67, 0.006778178637804745, 147),
 (138, 'rp', 'Philippines', 300000, 298170, 1830, 100998376, 1.61, 24.27, 6.11, 2.09, 0.006137438374081899, 162),
 (86, 'jo', 'Jordan', 89342, 88802, 540, 8117564, 0.83, 25.37, 3.79, 13.24, 0.006080944122880115, 164),
 (158, 'si', 'Slovenia', 20273, 20151, 122, 1983412, 0.26, 8.42, 11.37, 0.37, 0.006054290109671977, 165),
 (53, 'eg', 'Egypt', 1001450, 995450, 6000, 88487396, 1.79, 22.9, 4.77, 0.19, 0.006027424782761565, 165),
 (31, 'cm', 'Cameroon', 475440, 472710, 2730, 23739218, 2.59, 36.17, 10.11, 0.15, 0.005775211017325633, 173),
 (61, 'fr', 'France', 643801, 640427, 3374, 66553766, 0.43, 12.38, 9.16, 1.09, 0.005268360016051791, 189),
 (113, 'mp', 'Mauritius', 2040, 2030, 10, 1339827, 0.64, 13.29, 6.91, 0.0, 0.0049261083743842365, 203),
 (173, 'th', 'Thailand', 513120, 510890, 2230, 67976405, 0.34, 11.19, 7.8, 0.0, 0.004364931785707295, 229),
 (137, 'pe', 'Peru', 1285216, 1279996, 5220, 30444999, 0.97, 18.28, 6.01, 2.53, 0.004078137744180451, 245),
 (161, 'sf', 'South Africa', 1219090, 1214470, 4620, 53675563, 1.33, 20.75, 9.91, 2.42, 0.0038041285499024265, 262),
 (107, 'my', 'Malaysia', 329847, 328657, 1190, 30513848, 1.44, 19.71, 5.03, 0.33, 0.0036207961491768015, 276),
 (148, 'ws', 'Samoa', 2831, 2821, 10, 197773, 0.58, 20.87, 5.32, 9.78, 0.003544842254519674, 282),
 (80, 'iz', 'Iraq', 438317, 437367, 950, 37056169, 2.93, 31.45, 3.77, 1.62, 0.0021720888864500522, 460),
 (74, 'ho', 'Honduras', 112090, 111890, 200, 8746673, 1.68, 23.14, 5.17, 1.16, 0.00178746983644651, 559),
 (155, 'sl', 'Sierra Leone', 71740, 71620, 120, 5879098, 2.35, 37.03, 10.81, 2.77, 0.0016755096341803965, 596),
 (41, 'cf', 'Congo, Republic of the', 342000, 341500, 500, 4755097, 2.0, 35.85, 10.0, 5.9, 0.0014641288433382138, 683),
 (27, 'uv', 'Burkina Faso', 274200, 273800, 400, 18931686, 3.03, 42.03, 11.72, 0.0, 0.0014609203798392988, 684),
 (122, 'wa', 'Namibia', 824292, 823290, 1002, 2212307, 0.59, 19.8, 13.91, 0.0, 0.001217068104799038, 821),
 (46, 'cy', 'Cyprus', 9251, 9241, 10, 1189197, 1.43, 11.41, 6.62, 9.48, 0.0010821339681852614, 924),
 (90, 'kn', 'Korea, North', 120538, 120408, 130, 24983205, 0.53, 14.52, 9.21, 0.04, 0.0010796624808982792, 926),
 (49, 'dj', 'Djibouti', 23200, 23180, 20, 828324, 2.2, 23.65, 7.73, 6.06, 0.0008628127696289905, 1159),
 (42, 'cs', 'Costa Rica', 51100, 51060, 40, 4814144, 1.22, 15.91, 4.55, 0.83, 0.0007833920877399138, 1276),
 (70, 'gv', 'Guinea', 245857, 245717, 140, 11780162, 2.63, 35.74, 9.46, 0.0, 0.0005697611479873187, 1755),
 (120, 'mo', 'Morocco', 446550, 446300, 250, 33322699, 1.0, 18.2, 4.81, 3.36, 0.000560161326462021, 1785),
 (128, 'ng', 'Niger', None, 1266700, 300, 18045729, 3.25, 45.45, 12.42, 0.56, 0.00023683587274019106, 4222),
 (22, 'bk', 'Bosnia and Herzegovina', 51197, 51187, 10, 3867055, 0.13, 8.87, 9.75, 0.38, 0.0001953621036591322, 5118),
 (1, 'af', 'Afghanistan', 652230, 652230, 0, 32564342, 2.32, 38.57, 13.89, 1.51, 0.0, None),
 (3, 'ag', 'Algeria', 2381741, 2381741, 0, 39542166, 1.84, 23.67, 4.31, 0.92, 0.0, None),
 (4, 'an', 'Andorra', 468, 468, 0, 85580, 0.12, 8.13, 6.96, 0.0, 0.0, None),
 (5, 'ao', 'Angola', 1246700, 1246700, 0, 19625353, 2.78, 38.78, 11.49, 0.46, 0.0, None),
 (6, 'ac', 'Antigua and Barbuda', 442, 442, 0, 92436, 1.24, 15.85, 5.69, 2.21, 0.0, None),
 (13, 'ba', 'Bahrain', 760, 760, 0, 1346613, 2.41, 13.66, 2.69, 13.09, 0.0, None),
 (15, 'bb', 'Barbados', 430, 430, 0, 290604, 0.31, 11.87, 8.44, 0.3, 0.0, None),
 (20, 'bt', 'Bhutan', 38394, 38394, 0, 741919, 1.11, 17.78, 6.69, 0.0, 0.0, None),
 (33, 'cv', 'Cabo Verde', 4033, 4033, 0, 545993, 1.36, 20.33, 6.11, 0.63, 0.0, None),
 (34, 'ct', 'Central African Republic', 622984, 622984, 0, 5391539, 2.13, 35.08, 13.8, 0.0, 0.0, None),
 (39, 'cn', 'Comoros', 2235, 2235, 0, 780971, 1.77, 27.84, 7.57, 2.53, 0.0, None),
 (50, 'do', 'Dominica', 751, 751, 0, 73607, 0.21, 15.41, 7.91, 5.38, 0.0, None),
 (55, 'ek', 'Equatorial Guinea', 28051, 28051, 0, 740743, 2.51, 33.31, 8.19, 0.0, 0.0, None),
 (59, 'fj', 'Fiji', 18274, 18274, 0, 909389, 0.67, 19.43, 6.04, 6.75, 0.0, None),
 (64, 'gg', 'Georgia', 69700, 69700, 0, 4931226, 0.08, 12.74, 10.82, 2.7, 0.0, None),
 (68, 'gj', 'Grenada', 344, 344, 0, 110694, 0.48, 16.03, 8.08, 3.13, 0.0, None),
 (89, 'kr', 'Kiribati', 811, 811, 0, 105711, 1.15, 21.46, 7.12, 2.87, 0.0, None),
 (92, 'kv', 'Kosovo', 10887, 10887, 0, 1870981, None, None, None, None, 0.0, None),
 (93, 'ku', 'Kuwait', 17818, 17818, 0, 2788534, 1.62, 19.91, 2.18, 1.58, 0.0, None),
 (98, 'lt', 'Lesotho', 30355, 30355, 0, 1947701, 0.32, 25.47, 14.89, 7.36, 0.0, None),
 (100, 'ly', 'Libya', 1759540, 1759540, 0, 6411776, 2.23, 18.03, 3.58, 7.8, 0.0, None),
 (101, 'ls', 'Liechtenstein', 160, 160, 0, 37624, 0.84, 10.45, 7.12, 5.08, 0.0, None),
 (103, 'lu', 'Luxembourg', 2586, 2586, 0, 570252, 2.13, 11.37, 7.24, 17.16, 0.0, None),
 (108, 'mv', 'Maldives', 298, 298, 0, 393253, 0.08, 15.75, 3.89, 12.68, 0.0, None),
 (110, 'mt', 'Malta', 316, 316, 0, 413965, 0.31, 10.18, 9.09, 1.98, 0.0, None),
 (111, 'rm', 'Marshall Islands', 181, 181, 0, 72191, 1.66, 25.6, 4.21, 4.83, 0.0, None),
 (112, 'mr', 'Mauritania', 1030700, 1030700, 0, 3596702, 2.23, 31.34, 8.2, 0.83, 0.0, None),
 (115, 'fm', 'Micronesia, Federated States of', 702, 702, 0, 105216, 0.46, 20.54, 4.23, 20.93, 0.0, None),
 (117, 'mn', 'Monaco', 2, 2, 0, 30535, 0.12, 6.65, 9.24, 3.83, 0.0, None),
 (123, 'nr', 'Nauru', 21, 21, 0, 9540, 0.55, 24.95, 5.87, 13.63, 0.0, None),
 (131, 'mu', 'Oman', 309500, 309500, 0, 3286936, 2.07, 24.44, 3.36, 0.43, 0.0, None),
 (133, 'ps', 'Palau', 459, 459, 0, 21265, 0.38, 11.05, 7.99, 0.71, 0.0, None),
 (141, 'qa', 'Qatar', 11586, 11586, 0, 2194817, 3.07, 9.84, 1.53, 22.39, 0.0, None),
 (145, 'sc', 'Saint Kitts and Nevis', 261, 261, 0, 51936, 0.76, 13.5, 7.09, 1.21, 0.0, None),
 (147, 'vc', 'Saint Vincent and the Grenadines', 389, 389, 0, 102627, 0.28, 13.57, 7.18, 9.17, 0.0, None),
 (149, 'sm', 'San Marino', 61, 61, 0, 33020, 0.82, 8.63, 8.45, 8.03, 0.0, None),
 (150, 'tp', 'Sao Tome and Principe', 964, 964, 0, 194006, 1.84, 34.23, 7.24, 8.63, 0.0, None),
 (151, 'sa', 'Saudi Arabia', 2149690, 2149690, 0, 27752316, 1.46, 18.51, 3.33, 0.55, 0.0, None),
 (153, 'ri', 'Serbia', 77474, 77474, 0, 7176794, 0.46, 9.08, 13.66, 0.0, 0.0, None),
 (154, 'se', 'Seychelles', 455, 455, 0, 92430, 0.83, 14.19, 6.89, 1.0, 0.0, None),
 (174, 'tt', 'Timor-Leste', 14874, 14874, 0, 1231116, 2.42, 34.16, 6.1, 3.86, 0.0, None),
 (177, 'td', 'Trinidad and Tobago', 5128, 5128, 0, 1222363, 0.13, 13.46, 8.56, 6.25, 0.0, None),

In [11]:
%%sql
--Finding which countries have more water than land

SELECT *,CAST(area_water AS FLOAT)/area_land as water_land_ratio, 
CAST(area_land as FLOAT)/area_water as land_water_ratio FROM facts
WHERE water_land_ratio>1
ORDER BY water_land_ratio DESC

 * sqlite:///factbook.db
Done.

[(228, 'io', 'British Indian Ocean Territory', 54400, 60, 54340, None, None, None, None, None, 905.6666666666666, 0.001104158998895841),
 (247, 'vq', 'Virgin Islands', 1910, 346, 1564, 103574, 0.59, 10.31, 8.54, 7.67, 4.520231213872832, 0.22122762148337596)]

In [12]:
%%sql
/*Finding which countries are adding the most people to their
populations, excluding 'World' and 'None' values*/

SELECT *,population*population_growth/100 as people_added
FROM facts
WHERE people_added<>'None' and name<>'World'
ORDER BY people_added DESC

 * sqlite:///factbook.db
Done.

[(77, 'in', 'India', 3287263, 2973193, 314070, 1251695584, 1.22, 19.55, 7.32, 0.04, 15270686.1248),
 (37, 'ch', 'China', 9596960, 9326410, 270550, 1367485388, 0.45, 12.49, 7.53, 0.44, 6153684.246),
 (129, 'ni', 'Nigeria', 923768, 910768, 13000, 181562056, 2.45, 37.64, 12.9, 0.22, 4448270.372),
 (132, 'pk', 'Pakistan', 796095, 770875, 25220, 199085847, 1.46, 22.58, 6.49, 1.54, 2906653.3662),
 (58, 'et', 'Ethiopia', 1104300, None, 104300, 99465819, 2.89, 37.27, 8.19, 0.22, 2874562.1691),
 (14, 'bg', 'Bangladesh', 148460, 130170, 18290, 168957745, 1.6, 21.14, 5.61, 0.46, 2703323.92),
 (186, 'us', 'United States', 9826675, 9161966, 664709, 321368864, 0.78, 12.49, 8.15, 3.86, 2506677.1392),
 (78, 'id', 'Indonesia', 1904569, 1811569, 93000, 255993674, 0.92, 16.72, 6.37, 1.16, 2355141.8008000003),
 (40, 'cg', 'Congo, Democratic Republic of the', 2344858, 2267048, 77810, 79375136, 2.45, 34.88, 10.07, 0.27, 1944690.8320000002),
 (138, 'rp', 'Philippines', 300000, 298170, 1830, 100998376, 1.61, 24.27, 6.11, 2.09, 1626073.8536),
 (53, 'eg', 'Egypt', 1001450, 995450, 6000, 88487396, 1.79, 22.9, 4.77, 0.19, 1583924.3884),
 (24, 'br', 'Brazil', 8515770, 8358140, 157630, 204259812, 0.77, 14.46, 6.58, 0.14, 1572800.5524000002),
 (114, 'mx', 'Mexico', 1964375, 1943945, 20430, 121736809, 1.18, 18.78, 5.26, 1.68, 1436494.3462),
 (172, 'tz', 'Tanzania', 947300, 885800, 61500, 51045882, 2.79, 36.39, 8.0, 0.54, 1424180.1078),
 (197, 'ee', 'European Union', 4324782, None, None, 513949445, 0.25, 10.2, 10.2, 2.5, 1284873.6125),
 (182, 'ug', 'Uganda', 241038, 197100, 43938, 37101745, 3.24, 43.79, 10.69, 0.74, 1202096.5380000002),
 (80, 'iz', 'Iraq', 438317, 437367, 950, 37056169, 2.93, 31.45, 3.77, 1.62, 1085745.7517),
 (179, 'tu', 'Turkey', 783562, 769632, 13930, 79414269, 1.26, 16.33, 5.88, 2.16, 1000619.7894),
 (79, 'ir', 'Iran', 1648195, 1531595, 116600, 81824270, 1.2, 17.99, 5.94, 0.07, 981891.24),
 (192, 'vm', 'Vietnam', 331210, 310070, 21140, 94348835, 0.97, 15.96, 5.93, 0.3, 915183.6995),
 (88, 'ke', 'Kenya', 580367, 569140, 11227, 45925301, 1.93, 26.4, 6.89, 0.22, 886358.3093),
 (1, 'af', 'Afghanistan', 652230, 652230, 0, 32564342, 2.32, 38.57, 13.89, 1.51, 755492.7344),
 (3, 'ag', 'Algeria', 2381741, 2381741, 0, 39542166, 1.84, 23.67, 4.31, 0.92, 727575.8544),
 (161, 'sf', 'South Africa', 1219090, 1214470, 4620, 53675563, 1.33, 20.75, 9.91, 2.42, 713884.9879000001),
 (193, 'ym', 'Yemen', 527968, 527968, 0, 26737317, 2.47, 29.98, 6.28, 1.0, 660411.7299),
 (165, 'su', 'Sudan', 1861484, None, None, 36108853, 1.72, 29.19, 7.66, 4.29, 621072.2716),
 (121, 'mz', 'Mozambique', 799380, 786380, 13000, 25303113, 2.45, 38.58, 12.1, 1.98, 619926.2685),
 (31, 'cm', 'Cameroon', 475440, 472710, 2730, 23739218, 2.59, 36.17, 10.11, 0.15, 614845.7461999999),
 (105, 'ma', 'Madagascar', 587041, 581540, 5501, 23812681, 2.58, 32.61, 6.81, 0.0, 614367.1698),
 (106, 'mi', 'Malawi', 118484, 94080, 24404, 17964697, 3.32, 41.56, 8.41, 0.0, 596427.9404),
 (128, 'ng', 'Niger', None, 1266700, 300, 18045729, 3.25, 45.45, 12.42, 0.56, 586486.1925),
 (66, 'gh', 'Ghana', 238533, 227533, 11000, 26327649, 2.18, 31.09, 7.22, 2.02, 573942.7482),
 (27, 'uv', 'Burkina Faso', 274200, 273800, 400, 18931686, 3.03, 42.03, 11.72, 0.0, 573630.0858),
 (28, 'bm', 'Burma', 676578, 653508, 23070, 56320206, 1.01, 18.39, 7.96, 0.28, 568834.0806),
 (124, 'np', 'Nepal', 147181, 143351, 3830, 31551305, 1.79, 20.64, 6.56, 3.86, 564768.3595),
 (5, 'ao', 'Angola', 1246700, 1246700, 0, 19625353, 2.78, 38.78, 11.49, 0.46, 545584.8134),
 (109, 'ml', 'Mali', 1240192, 1220190, 20002, 16955536, 2.98, 44.99, 12.89, 2.26, 505274.9728),
 (38, 'co', 'Colombia', 1138910, 1038700, 100210, 46736728, 1.04, 16.47, 5.4, 0.64, 486061.9712),
 (162, 'od', 'South Sudan', 644329, None, None, 12042910, 4.02, 36.91, 8.18, 11.47, 484124.98199999996),
 (43, 'iv', "Cote d'Ivoire", 322463, 318003, 4460, 23295302, 1.91, 28.67, 9.55, 0.0, 444940.2682),
 (107, 'my', 'Malaysia', 329847, 328657, 1190, 30513848, 1.44, 19.71, 5.03, 0.33, 439399.4112),
 (194, 'za', 'Zambia', 752618, 743398, 9220, 15066266, 2.88, 42.13, 12.67, 0.68, 433908.4608),
 (163, 'sp', 'Spain', 505370, 498980, 6390, 48146134, 0.89, 9.64, 9.04, 8.31, 428500.5926),
 (191, 've', 'Venezuela', 912050, 882050, 30000, 29275460, 1.39, 19.16, 5.31, 0.0, 406928.894),
 (151, 'sa', 'Saudi Arabia', 2149690, 2149690, 0, 27752316, 1.46, 18.51, 3.33, 0.55, 405183.8136),
 (7, 'ar', 'Argentina', 2780400, 2736690, 43710, 43431886, 0.93, 16.64, 7.33, 0.0, 403916.5398),
 (29, 'by', 'Burundi', 27830, 25680, 2150, 10742276, 3.28, 42.01, 9.27, 0.0, 352346.65280000004),
 (185, 'uk', 'United Kingdom', 243610, 241930, 1680, 64088222, 0.54, 12.17, 9.35, 2.54, 346076.3988),
 (152, 'sg', 'Senegal', 196722, 192530, 4192, 13975834, 2.45, 34.52, 8.46, 1.59, 342407.933),
 (120, 'mo', 'Morocco', 446550, 446300, 250, 33322699, 1.0, 18.2, 4.81, 3.36, 333226.99),
 (144, 'rw', 'Rwanda', 26338, 24668, 1670, 12661733, 2.56, 33.75, 8.96, 0.85, 324140.3648),
 (195, 'zi', 'Zimbabwe', 390757, 386847, 3910, 14229541, 2.21, 32.26, 10.13, 0.0, 314472.8561),
 (70, 'gv', 'Guinea', 245857, 245717, 140, 11780162, 2.63, 35.74, 9.46, 0.0, 309818.2606),
 (137, 'pe', 'Peru', 1285216, 1279996, 5220, 30444999, 0.97, 18.28, 6.01, 2.53, 295316.49029999995),
 (19, 'bn', 'Benin', 112622, 110622, 2000, 10448647, 2.78, 36.02, 8.21, 0.0, 290472.38659999997),
 (61, 'fr', 'France', 643801, 640427, 3374, 66553766, 0.43, 12.38, 9.16, 1.09, 286181.1938),
 (188, 'uz', 'Uzbekistan', 447400, 425400, 22000, 29199942, 0.93, 17.0, 5.3, 2.37, 271559.46060000005),
 (69, 'gt', 'Guatemala', 108889, 107159, 1730, 14918999, 1.82, 24.89, 4.77, 1.97, 271525.7818),
 (183, 'up', 'Ukraine', 603550, 579330, 24220, 44429471, 0.6, 10.72, 14.46, 2.25, 266576.826),
 (32, 'ca', 'Canada', 9984670, 9093507, 891163, 35099836, 0.75, 10.28, 8.42, 5.66, 263248.77),
 (30, 'cb', 'Cambodia', 181035, 176515, 4520, 15708756, 1.58, 23.83, 7.68, 0.32, 248198.3448),
 (9, 'as', 'Australia', 7741220, 7682300, 58920, 22751014, 1.07, 12.15, 7.14, 5.65, 243435.8498),
 (173, 'th', 'Thailand', 513120, 510890, 2230, 67976405, 0.34, 11.19, 7.8, 0.0, 231119.77700000003),
 (35, 'cd', 'Chad', None, 1259200, 24800, 11631456, 1.89, 36.6, 14.28, 3.45, 219834.5184),
 (52, 'ec', 'Ecuador', 283561, 276841, 6720, 15868396, 1.35, 18.51, 5.06, 0.0, 214223.34600000002),
 (87, 'kz', 'Kazakhstan', 2724900, 2699700, 25200, 18157122, 1.14, 19.15, 8.21, 0.41, 206991.19079999998),
 (175, 'to', 'Togo', 56785, 54385, 2400, 7552318, 2.69, 34.13, 7.26, 0.0, 203157.35419999997),
 (85, 'ja', 'Japan', 377915, 364485, 13430, 126919659, 0.16, 7.93, 9.51, 0.0, 203071.45440000002),
 (160, 'so', 'Somalia', 637657, 627337, 10320, 10616380, 1.83, 40.45, 13.62, 8.49, 194279.75400000002),
 (164, 'ce', 'Sri Lanka', 65610, 64630, 980, 22053488, 0.84, 15.85, 6.11, 1.35, 185249.29919999998),
 (21, 'bl', 'Bolivia', 1098581, 1083301, 15280, 10800882, 1.56, 22.76, 6.52, 0.62, 168493.75920000003),
 (83, 'it', 'Italy', 301340, 294140, 7200, 61855120, 0.27, 8.74, 10.19, 4.1, 167008.824),
 (184, 'ae', 'United Arab Emirates', 83600, 83600, 0, 5779760, 2.58, 15.43, 1.97, 12.36, 149117.80800000002),
 (74, 'ho', 'Honduras', 112090, 111890, 200, 8746673, 1.68, 23.14, 5.17, 1.16, 146944.1064),
 (56, 'er', 'Eritrea', 117600, 101000, 16600, 6527689, 2.25, 30.0, 7.52, 0.0, 146873.0025),
 (36, 'ci', 'Chile', 756102, 743812, 12290, 17508260, 0.82, 13.83, 6.0, 0.34, 143567.732),
 (100, 'ly', 'Libya', 1759540, 1759540, 0, 6411776, 2.23, 18.03, 3.58, 7.8, 142982.6048),
 (171, 'ti', 'Tajikistan', 144100, 141510, 2590, 8191958, 1.71, 24.38, 6.18, 1.15, 140082.4818),
 (155, 'sl', 'Sierra Leone', 71740, 71620, 120, 5879098, 2.35, 37.03, 10.81, 2.77, 138158.803),
 (65, 'gm', 'Germany', 357022, 348672, 8350, 80854408, 0.17, 8.47, 11.42, 1.24, 137452.49360000002),
 (90, 'kn', 'Korea, North', 120538, 120408, 130, 24983205, 0.53, 14.52, 9.21, 0.04, 132410.9865),
 (51, 'dr', 'Dominican Republic', 48670, 48320, 350, 10478756, 1.23, 18.73, 4.55, 1.91, 128888.69879999998),
 (82, 'is', 'Israel', 20770, 20330, 440, 8049314, 1.56, 18.48, 5.15, 2.24, 125569.2984),
 (135, 'pp', 'Papua New Guinea', 462840, 452860, 9980, 6672429, 1.78, 24.38, 6.53, 0.0, 118769.23620000001),
 (73, 'ha', 'Haiti', 27750, 27560, 190, 10110019, 1.17, 22.31, 7.83, 2.76, 118287.22229999998),
 (34, 'ct', 'Central African Republic', 622984, 622984, 0, 5391539, 2.13, 35.08, 13.8, 0.0, 114839.7807),
 (156, 'sn', 'Singapore', 697, 687, 10, 5674472, 1.89, 8.27, 3.43, 14.05, 107247.5208),
 (95, 'la', 'Laos', 236800, 230800, 6000, 6911544, 1.55, 24.25, 7.63, 1.09, 107128.93200000002),
 (99, 'li', 'Liberia', 111369, 96320, 15049, 4195666, 2.47, 34.41, 9.69, 0.0, 103632.95020000002),
 (178, 'ts', 'Tunisia', 163610, 155360, 8250, 11037225, 0.89, 16.64, 5.98, 1.73, 98231.3025),
 (41, 'cf', 'Congo, Republic of the', 342000, 341500, 500, 4755097, 2.0, 35.85, 10.0, 5.9, 95101.94),
 (11, 'aj', 'Azerbaijan', 86600, 82629, 3971, 9780780, 0.96, 16.64, 7.07, 0.0, 93895.48799999998),
 (17, 'be', 'Belgium', 30528, 30278, 250, 11323973, 0.76, 11.41, 9.63, 5.87, 86062.1948),
 (112, 'mr', 'Mauritania', 1030700, 1030700, 0, 3596702, 2.23, 31.34, 8.2, 0.83, 80206.4546),
 (136, 'pa', 'Paraguay', 406752, 397302, 9450, 6783272, 1.16, 16.37, 4.68, 0.07, 78685.9552),
 (168, 'sw', 'Sweden', 450295, 410335, 39960, 9801616, 0.8, 11.99, 9.4, 5.42, 78412.92800000001),
 (125, 'nl', 'Netherlands', 41543, 33893, 7650, 16947904, 0.41, 10.83, 8.66, 1.95, 69486.40639999999),
 (91, 'ks', 'Korea, South', 99720, 96920, 2800, 49115196, 0.14, 8.19, 6.75, 0.0, 68761.27440000001),
 (131, 'mu', 'Oman', 309500, 309500, 0, 3286936, 2.07, 24.44, 3.36, 0.43, 68039.57519999999),
 (141, 'qa', 'Qatar', 11586, 11586, 0, 2194817, 3.07, 9.84, 1.53, 22.39, 67380.8819),
 (86, 'jo', 'Jordan', 89342, 88802, 540, 8117564, 0.83, 25.37, 3.79, 13.24, 67375.7812),
 (142, 'ro', 'Romania', 238391, 229891, 8500, 21666350, 0.3, 9.14, 11.9, 0.24, 64999.05),
 (94, 'kg', 'Kyrgyzstan', 199951, 191801, 8150, 5664939, 1.11, 22.98, 6.65, 5.22, 62880.82290000001),
 (81, 'ei', 'Ireland', 70273, 68883, 1390, 4892305, 1.25, 14.84, 6.48, 4.09, 61153.8125),
 (180, 'tx', 'Turkmenistan', 488100, 469930, 18170, 5231422, 1.14, 19.4, 6.13, 1.84, 59638.21079999999),
 (127, 'nu', 'Nicaragua', 130370, 119990, 10380, 5907881, 1.0, 18.03, 5.08, 3.0, 59078.81),
 (130, 'no', 'Norway', 323802, 304282, 19520, 5207689, 1.13, 12.14, 8.12, 7.25, 58846.88569999999),
 (42, 'cs', 'Costa Rica', 51100, 51060, 40, 4814144, 1.22, 15.91, 4.55, 0.83, 58732.5568),
 (169, 'sz', 'Switzerland', 41277, 39997, 1280, 8121830, 0.71, 10.5, 8.13, 4.74, 57664.992999999995),
 (143, 'rs', 'Russia', 17098242, 16377742, 720500, 142423773, 0.04, 11.6, 13.69, 1.69, 56969.5092),
 (254, 'we', 'West Bank', 5860, 5640, 220, 2785366, 1.95, 22.99, 3.5, 0.0, 54314.637),
 (196, 'tw', 'Taiwan', 35980, 32260, 3720, 23415126, 0.23, 8.47, 7.11, 0.89, 53854.789800000006),
 (97, 'le', 'Lebanon', 10400, 10230, 170, 6184701, 0.86, 14.59, 4.88, 1.1, 53188.42860000001),
 (251, 'gz', 'Gaza Strip', 360, 360, 0, 1869055, 2.81, 31.11, 3.04, 0.0, 52520.4455),
 (134, 'pm', 'Panama', 75420, 74340, 1080, 3657024, 1.32, 18.32, 4.81, 0.28, 48272.71680000001),
 (10, 'au', 'Austria', 83871, 82445, 1426, 8665550, 0.55, 9.41, 9.42, 5.56, 47660.525),
 (93, 'ku', 'Kuwait', 17818, 17818, 0, 2788534, 1.62, 19.91, 2.18, 1.58, 45174.2508),
 (63, 'ga', 'Gambia, The', 11300, 10120, 1180, 1967709, 2.16, 30.86, 7.15, 2.12, 42502.51440000001),
 (26, 'bu', 'Bulgaria', 110879, 108489, 2390, 7186893, 0.58, 8.92, 14.44, 0.29, 41683.9794),
 (118, 'mg', 'Mongolia', 1564116, 1553556, 10560, 2992908, 1.31, 20.25, 6.35, 0.84, 39207.0948),
 (116, 'md', 'Moldova', 33851, 32891, 960, 3546847, 1.03, 12.0, 12.59, 9.67, 36532.5241),
 (126, 'nz', 'New Zealand', 267710, 267710, None, 4438393, 0.82, 13.33, 7.36, 2.21, 36394.8226),
 (139, 'pl', 'Poland', 312685, 304255, 8430, 38562189, 0.09, 9.74, 10.19, 0.46, 34705.9701),
 (153, 'ri', 'Serbia', 77474, 77474, 0, 7176794, 0.46, 9.08, 13.66, 0.0, 33013.252400000005),
 (71, 'pu', 'Guinea-Bissau', 36125, 28120, 8005, 1726170, 1.91, 33.38, 14.33, 0.0, 32969.846999999994),
 (62, 'gb', 'Gabon', 267667, 257667, 10000, 1705336, 1.93, 34.49, 13.12, 2.03, 32912.9848),
 (13, 'ba', 'Bahrain', 760, 760, 0, 1346613, 2.41, 13.66, 2.69, 13.09, 32453.3733),
 (102, 'lh', 'Lithuania', 65300, 62680, 2620, 2884433, 1.04, 10.1, 14.27, 6.27, 29998.1032),
 (174, 'tt', 'Timor-Leste', 14874, 14874, 0, 1231116, 2.42, 34.16, 6.1, 3.86, 29793.007199999996),
 (170, 'sy', 'Syria', 185180, 183630, 1550, 17064854, 0.16, 22.17, 4.0, 19.79, 27303.7664),
 (204, 'hk', 'Hong Kong', 1108, 1073, 35, 7141106, 0.38, 9.23, 7.07, 1.68, 27136.202800000003),
 (23, 'bc', 'Botswana', 581730, 566730, 15000, 2182719, 1.21, 20.96, 13.39, 4.56, 26410.899899999997),
 (60, 'fi', 'Finland', 338145, 303815, 34330, 5476922, 0.4, 10.72, 9.83, 3.1, 21907.688000000002),
 (75, 'hu', 'Hungary', 93028, 89608, 3420, 9897541, 0.22, 9.16, 12.73, 1.33, 21774.5902),
 (246, 'rq', 'Puerto Rico', 13791, 8870, 4921, 3598357, 0.6, 10.86, 8.67, 8.15, 21590.141999999996),
 (96, 'lg', 'Latvia', 64589, 62249, 2340, 1986705, 1.06, 10.0, 14.31, 6.26, 21059.073000000004),
 (84, 'jm', 'Jamaica', 10991, 10831, 160, 2950210, 0.68, 18.16, 6.7, 4.66, 20061.428),
 (16, 'bo', 'Belarus', 207600, 202900, 4700, 9589689, 0.2, 10.7, 13.36, 0.7, 19179.378),
 (55, 'ek', 'Equatorial Guinea', 28051, 28051, 0, 740743, 2.51, 33.31, 8.19, 0.0, 18592.6493),
 (49, 'dj', 'Djibouti', 23200, 23180, 20, 828324, 2.2, 23.65, 7.73, 6.06, 18223.128),
 (47, 'ez', 'Czech Republic', 78867, 77247, 1620, 10644842, 0.16, 9.63, 10.34, 2.33, 17031.747199999998),
 (46, 'cy', 'Cyprus', 9251, 9241, 10, 1189197, 1.43, 11.41, 6.62, 9.48, 17005.5171),
 (45, 'cu', 'Cuba', 110860, 109820, 1040, 11031433, 0.15, 9.9, 7.72, 3.66, 16547.1495),
 (255, 'wi', 'Western Sahara', 266000, 266000, 0, 570866, 2.82, 30.24, 8.34, None, 16098.421199999999),
 (167, 'wz', 'Swaziland', 17364, 17204, 160, 1435613, 1.11, 24.67, 13.56, 0.0, 15935.304300000002),
 (54, 'es', 'El Salvador', 21041, 20721, 320, 6141350, 0.25, 16.46, 5.69, 8.28, 15353.375),
 (39, 'cn', 'Comoros', 2235, 2235, 0, 780971, 1.77, 27.84, 7.57, 2.53, 13823.186699999998),
 (122, 'wa', 'Namibia', 824292, 823290, 1002, 2212307, 0.59, 19.8, 13.91, 0.0, 13052.611299999999),
 (159, 'bp', 'Solomon Islands', 28896, 27986, 910, 622469, 2.02, 25.77, 3.85, 1.75, 12573.873800000001),
 (48, 'da', 'Denmark', 43094, 42434, 660, 5581503, 0.22, 10.27, 10.25, 2.2, 12279.3066),
 (103, 'lu', 'Luxembourg', 2586, 2586, 0, 570252, 2.13, 11.37, 7.24, 17.16, 12146.3676),
 (140, 'po', 'Portugal', 92090, 91470, 620, 10825309, 0.09, 9.27, 11.02, 2.67, 9742.7781),
 (2, 'al', 'Albania', 28748, 27398, 1350, 3029278, 0.3, 12.92, 6.58, 3.3, 9087.834),
 (187, 'uy', 'Uruguay', 176215, 175015, 1200, 3341893, 0.27, 13.07, 9.45, 0.9, 9023.111100000002),
 (113, 'mp', 'Mauritius', 2040, 2030, 10, 1339827, 0.64, 13.29, 6.91, 0.0, 8574.8928),
 (20, 'bt', 'Bhutan', 38394, 38394, 0, 741919, 1.11, 17.78, 6.69, 0.0, 8235.3009),
 (33, 'cv', 'Cabo Verde', 4033, 4033, 0, 545993, 1.36, 20.33, 6.11, 0.63, 7425.504800000001),
 (25, 'bx', 'Brunei', 5765, 5265, 500, 429646, 1.62, 17.32, 3.52, 2.43, 6960.2652),
 (57, 'en', 'Estonia', 45228, 42388, 2840, 1265420, 0.55, 10.51, 12.4, 3.6, 6959.81),
 (18, 'bh', 'Belize', 22966, 22806, 160, 347369, 1.87, 24.68, 5.97, 0.0, 6495.8003),
 (166, 'ns', 'Suriname', 163820, 156000, 7820, 579633, 1.08, 16.34, 6.13, 0.56, 6260.0364),
 (98, 'lt', 'Lesotho', 30355, 30355, 0, 1947701, 0.32, 25.47, 14.89, 7.36, 6232.6432),
 (59, 'fj', 'Fiji', 18274, 18274, 0, 909389, 0.67, 19.43, 6.04, 6.75, 6092.9063),
 (44, 'hr', 'Croatia', 56594, 55974, 620, 4464844, 0.13, 9.45, 12.18, 1.39, 5804.2972),
 (189, 'nh', 'Vanuatu', 12189, 12189, 0, 272264, 1.95, 25.04, 4.09, 1.47, 5309.147999999999),
 (158, 'si', 'Slovenia', 20273, 20151, 122, 1983412, 0.26, 8.42, 11.37, 0.37, 5156.8712),
 (22, 'bk', 'Bosnia and Herzegovina', 51197, 51187, 10, 3867055, 0.13, 8.87, 9.75, 0.38, 5027.1715),
 (205, 'mc', 'Macau', 28, 28, 0, 592731, 0.8, 8.88, 4.22, 3.37, 4741.848000000001),
 (8, 'am', 'Armenia', 29743, 28203, 1540, 3056382, 0.15, 13.61, 9.34, 5.8, 4584.573),
 (104, 'mk', 'Macedonia', 25713, 25433, 280, 2096015, 0.2, 11.55, 9.08, 0.48, 4192.03),
 (76, 'ic', 'Iceland', 103000, 100250, 2750, 331918, 1.21, 13.91, 6.28, 4.43, 4016.2077999999997),
 (64, 'gg', 'Georgia', 69700, 69700, 0, 4931226, 0.08, 12.74, 10.82, 2.7, 3944.9808000000003),
 (211, 'nc', 'New Caledonia', 18575, 18275, 300, 271615, 1.38, 15.33, 5.52, 4.01, 3748.2869999999994),
 (150, 'tp', 'Sao Tome and Principe', 964, 964, 0, 194006, 1.84, 34.23, 7.24, 8.63, 3569.7104000000004),
 (12, 'bf', 'Bahamas, The', 13880, 10010, 3870, 324597, 0.85, 15.5, 7.05, 0.0, 2759.0745),
 (119, 'mj', 'Montenegro', 13812, 13452, 360, 647073, 0.42, 10.42, 9.43, None, 2717.7065999999995),
 (209, 'fp', 'French Polynesia', 4167, 3827, 340, 282703, 0.94, 15.22, 5.02, 0.84, 2657.4082),
 (177, 'td', 'Trinidad and Tobago', 5128, 5128, 0, 1222363, 0.13, 13.46, 8.56, 6.25, 1589.0719),
 (216, 'aa', 'Aruba', 180, 180, 0, 112162, 1.33, 12.56, 8.18, 8.92, 1491.7546000000002),
 (110, 'mt', 'Malta', 316, 316, 0, 413965, 0.31, 10.18, 9.09, 1.98, 1283.2915),
 (89, 'kr', 'Kiribati', 811, 811, 0, 105711, 1.15, 21.46, 7.12, 2.87, 1215.6765),
 (111, 'rm', 'Marshall Islands', 181, 181, 0, 72191, 1.66, 25.6, 4.21, 4.83, 1198.3706),
 (230, 'cj', 'Cayman Islands', 264, 264, 0, 56092, 2.1, 12.11, 5.53, 14.4, 1177.932),
 (241, 'tk', 'Turks and Caicos Islands', 948, 948, 0, 50280, 2.3, 16.13, 3.1, 9.94, 1156.4399999999998),
 (148, 'ws', 'Samoa', 2831, 2821, 10, 197773, 0.58, 20.87, 5.32, 9.78, 1147.0834),
 (6, 'ac', 'Antigua and Barbuda', 442, 442, 0, 92436, 1.24, 15.85, 5.69, 2.21, 1146.2064),
 (245, 'cq', 'Northern Mariana Islands', 464, 464, 0, 52344, 2.18, 18.32, 3.71, 7.16, 1141.0992),
 (157, 'lo', 'Slovakia', 49035, 48105, 930, 5445027, 0.02, 9.91, 9.74, 0.04, 1089.0054),
 (67, 'gr', 'Greece', 131957, 130647, 1310, 10775643, 0.01, 8.66, 11.09, 2.32, 1077.5643),
 (15, 'bb', 'Barbados', 430, 430, 0, 290604, 0.31, 11.87, 8.44, 0.3, 900.8724000000001),
 (243, 'gq', 'Guam', 544, 544, 0, 161785, 0.54, 16.82, 5.12, 6.34, 873.6390000000001),
 (235, 'je', 'Jersey', 116, 116, 0, 97294, 0.8, 11.91, 7.68, 3.76, 778.352),
 (229, 'vi', 'British Virgin Islands', 151, 151, 0, 33454, 2.32, 10.91, 4.99, 17.28, 776.1328),
 (154, 'se', 'Seychelles', 455, 455, 0, 92430, 0.83, 14.19, 6.89, 1.0, 767.169),
 (236, 'im', 'Isle of Man', 572, 572, 0, 87545, 0.76, 11.1, 10.06, 6.56, 665.342),
 (217, 'cc', 'Curacao', 444, 444, 0, 148406, 0.43, 13.8, 8.2, 1.4, 638.1458),
 (247, 'vq', 'Virgin Islands', 1910, 346, 1564, 103574, 0.59, 10.31, 8.54, 7.67, 611.0866),
 (218, 'sk', 'Sint Maarten', 34, 34, 0, 39689, 1.51, 13.0, 4.51, 6.63, 599.3039),
 (146, 'st', 'Saint Lucia', 616, 606, 10, 163922, 0.34, 13.7, 7.42, 2.93, 557.3348000000001),
 (68, 'gj', 'Grenada', 344, 344, 0, 110694, 0.48, 16.03, 8.08, 3.13, 531.3312),
 (115, 'fm', 'Micronesia, Federated States of', 702, 702, 0, 105216, 0.46, 20.54, 4.23, 20.93, 483.9936),
 (145, 'sc', 'Saint Kitts and Nevis', 261, 261, 0, 51936, 0.76, 13.5, 7.09, 1.21, 394.7136),
 (227, 'bd', 'Bermuda', 54, 54, 0, 70196, 0.5, 11.33, 8.23, 1.88, 350.98),
 (226, 'av', 'Anguilla', 91, 91, 0, 16418, 2.03, 12.67, 4.57, 12.18, 333.2853999999999),
 (101, 'ls', 'Liechtenstein', 160, 160, 0, 37624, 0.84, 10.45, 7.12, 5.08, 316.0416),
 (108, 'mv', 'Maldives', 298, 298, 0, 393253, 0.08, 15.75, 3.89, 12.68, 314.6024),
 (219, 'cw', 'Cook Islands', 236, 236, 0, 9838, 2.95, 14.33, 8.03, None, 290.221),
 (147, 'vc', 'Saint Vincent and the Grenadines', 389, 389, 0, 102627, 0.28, 13.57, 7.18, 9.17, 287.35560000000004),
 (149, 'sm', 'San Marino', 61, 61, 0, 33020, 0.82, 8.63, 8.45, 8.03, 270.76399999999995),
 (206, 'fo', 'Faroe Islands', 1393, 1393, 0, 50196, 0.51, 13.77, 8.71, 0.0, 255.9996),
 (234, 'gk', 'Guernsey', 78, 78, 0, 66080, 0.34, 9.84, 8.78, 2.32, 224.672),

In [13]:
%%sql

/*Finding which countries have a higher death-rate than
birth-rate, and ordering by the ratio of deaths to births*/

SELECT *,death_rate/birth_rate as loss_ratio FROM facts
WHERE death_rate>birth_rate
ORDER BY loss_ratio DESC

 * sqlite:///factbook.db
Done.

[(26, 'bu', 'Bulgaria', 110879, 108489, 2390, 7186893, 0.58, 8.92, 14.44, 0.29, 1.6188340807174888),
 (153, 'ri', 'Serbia', 77474, 77474, 0, 7176794, 0.46, 9.08, 13.66, 0.0, 1.5044052863436124),
 (96, 'lg', 'Latvia', 64589, 62249, 2340, 1986705, 1.06, 10.0, 14.31, 6.26, 1.431),
 (102, 'lh', 'Lithuania', 65300, 62680, 2620, 2884433, 1.04, 10.1, 14.27, 6.27, 1.4128712871287128),
 (75, 'hu', 'Hungary', 93028, 89608, 3420, 9897541, 0.22, 9.16, 12.73, 1.33, 1.3897379912663756),
 (117, 'mn', 'Monaco', 2, 2, 0, 30535, 0.12, 6.65, 9.24, 3.83, 1.3894736842105262),
 (158, 'si', 'Slovenia', 20273, 20151, 122, 1983412, 0.26, 8.42, 11.37, 0.37, 1.350356294536817),
 (183, 'up', 'Ukraine', 603550, 579330, 24220, 44429471, 0.6, 10.72, 14.46, 2.25, 1.3488805970149254),
 (65, 'gm', 'Germany', 357022, 348672, 8350, 80854408, 0.17, 8.47, 11.42, 1.24, 1.3482880755608027),
 (214, 'sb', 'Saint Pierre and Miquelon', 242, 242, 0, 5657, 1.08, 7.42, 9.72, 8.49, 1.3099730458221026),
 (142, 'ro', 'Romania', 238391, 229891, 8500, 21666350, 0.3, 9.14, 11.9, 0.24, 1.3019693654266957),
 (44, 'hr', 'Croatia', 56594, 55974, 620, 4464844, 0.13, 9.45, 12.18, 1.39, 1.288888888888889),
 (67, 'gr', 'Greece', 131957, 130647, 1310, 10775643, 0.01, 8.66, 11.09, 2.32, 1.2806004618937643),
 (16, 'bo', 'Belarus', 207600, 202900, 4700, 9589689, 0.2, 10.7, 13.36, 0.7, 1.2485981308411216),
 (85, 'ja', 'Japan', 377915, 364485, 13430, 126919659, 0.16, 7.93, 9.51, 0.0, 1.1992433795712485),
 (140, 'po', 'Portugal', 92090, 91470, 620, 10825309, 0.09, 9.27, 11.02, 2.67, 1.1887810140237325),
 (143, 'rs', 'Russia', 17098242, 16377742, 720500, 142423773, 0.04, 11.6, 13.69, 1.69, 1.1801724137931033),
 (57, 'en', 'Estonia', 45228, 42388, 2840, 1265420, 0.55, 10.51, 12.4, 3.6, 1.1798287345385348),
 (83, 'it', 'Italy', 301340, 294140, 7200, 61855120, 0.27, 8.74, 10.19, 4.1, 1.165903890160183),
 (22, 'bk', 'Bosnia and Herzegovina', 51197, 51187, 10, 3867055, 0.13, 8.87, 9.75, 0.38, 1.0992108229988726),
 (47, 'ez', 'Czech Republic', 78867, 77247, 1620, 10644842, 0.16, 9.63, 10.34, 2.33, 1.0737279335410175),
 (116, 'md', 'Moldova', 33851, 32891, 960, 3546847, 1.03, 12.0, 12.59, 9.67, 1.0491666666666666),
 (139, 'pl', 'Poland', 312685, 304255, 8430, 38562189, 0.09, 9.74, 10.19, 0.46, 1.0462012320328542),
 (10, 'au', 'Austria', 83871, 82445, 1426, 8665550, 0.55, 9.41, 9.42, 5.56, 1.0010626992561105)]